---
- name: "Install epel repository for RHEL & Centos"
  become: true
  ansible.builtin.package:
    name: "epel-release"
    state: "present"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != 'Fedora'

- name: "Enable PowerTools repository"
  become: true
  ansible.builtin.import_role:
    name: robertdebock.powertools
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != 'Fedora'

- name: "Install common packages for RHEL & Centos"
  become: true
  ansible.builtin.yum:
    name: "{{ common_packages }}"
    state: "present"
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: "Install common packages for Debian & Ubuntu"
  become: true
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: "present"
    update_cache: true
  when: ansible_os_family == "Debian"

- name: "Remove dhclient"
  become: true
  ansible.builtin.package:
    name: "dhclient"
    state: "absent"
  when: remove_dhclient | bool

- name: "Remove fwupd"
  become: true
  ansible.builtin.package:
    name: "fwupd"
    state: "absent"
  when: remove_fwupd | bool

- name: "Remove qemu-guest-agent"
  become: true
  ansible.builtin.package:
    name: "qemu-guest-agent "
    state: "absent"
  when: remove_qemu_guest_agent | bool
