---
- name: "Update kernel on CentOS & RedHat systems"
  become: True
  ansible.builtin.package:
    name: "kernel"
    state: "latest"  # noqa package-latest
  register: kernel_updated
  when: ansible_os_family == "RedHat"


- name: "Get Debian kernel architecture"
  ansible.builtin.set_fact:
    debian_linux_image_version: "{{ ansible_kernel | regex_replace('^.+-(.*)$', '\\1') }}"

- name: "Update kernel on Debian systems"
  become: True
  ansible.builtin.apt:
    name: "linux-image-{{ debian_linux_image_version }}"
    state: "latest"  # noqa package-latest
    update_cache: True
  register: kernel_updated
  when: ansible_os_family == "Debian" and ansible_distribution != 'Ubuntu'

- name: "Update kernel on Ubuntu systems"
  become: True
  ansible.builtin.apt:
    name: "linux-image-generic"
    state: "latest"  # noqa package-latest
    update_cache: True
  register: kernel_updated
  when: ansible_distribution == "Ubuntu"

- name: "Reboot the machine"
  become: True
  ansible.builtin.shell: 
    cmd: ( sleep 2s && shutdown -r now "Ansible updates triggered" & )
  register: shutdown_output
  changed_when: shutdown_output.rc == 0
  when:
    - allow_reboot|bool
    - kernel_updated.changed

- name: "Wait for machine to come back"
  ansible.builtin.wait_for_connection:
    timeout: 240
    delay: 20
  when:
    - allow_reboot|bool
    - kernel_updated.changed

- name: "Update all packages"
  become: True
  ansible.builtin.package:
    name: "*"
    state: "latest"  # noqa package-latest
